filter:
    excluded_paths:
        - 'logs/**'
        - 'local/config/**'
        - 'local/metadata/**'
tools:
    php_code_sniffer:
        config:
            standard: 'PSR2'
            sniffs: { generic: { formatting: { space_after_cast_sniff: true }, functions: { opening_function_brace_bsd_allman_sniff: true }, naming_conventions: { camel_caps_function_name_sniff: false } }, pear: { functions: { function_call_signature_sniff: false }, classes: { class_declaration_sniff: true } }, squiz: { scope: { member_var_scope_sniff: true }, classes: { lowercase_class_keywords_sniff: true, valid_class_name_sniff: false } }, psr1: { files: { side_effects_sniff: false }, classes: { class_declaration_sniff: false } }, psr2: { namespaces: { namespace_declaration_sniff: true } } }
    php_cpd: true
    php_pdepend: true